DOXYFILE = 'Doxyfile-mcss'
FAVICON = 'doxygen/favicon/favicon.ico'
MAIN_PROJECT_URL = 'https://whs31.github.io/floppy'
VERSION_LABELS = True
#FINE_PRINT = """<p>Taskflow handbook is part of the <a href="https://taskflow.github.io">Taskflow project</a>, copyright © <a href="https://tsung-wei-huang.github.io/">Dr. Tsung-Wei Huang</a>, 2018&ndash;2024.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>.</p>"""
LINKS_NAVBAR1 = [
  ("Handbook", 'pages', []),
  ("Modules", 'modules', []),
  ("Namespaces", 'namespaces', [])
]
